#!/usr/bin/env python3
"""
_run_T122_cables_and_trays.py — S011-T122 supplementary runner.

Produces the two remaining deliverables for T122 (count_only XLSX already
generated by run_T122_gpk3_count_only.py):

  (2) gpk3_software_cables_by_method.xlsx
      Cable totals from pdf_cables_by_method.CableMethodReport broken down by
      (cable_color x laying_method x cross_section). Canonical method labels:
        gofra_truba, lotok, po_konstrukciyam
      Columns: cable_mark, cable_color, laying_method, cross_section,
               unit, total_m

  (3) gpk3_software_trays.xlsx
      Cable-tray items extracted separately. We parse each Лотки* sheet's
      legend with pdf_legend_parser and keep only items whose description
      matches tray keywords from vor_generator._TRAY_KEYWORDS /
      _TRAY_ACCESSORY_KEYWORDS. Counts come from the previously generated
      equipment_report.json (which used the same legend symbols).

Run logs are appended to T122.md under .tayfa/common/discussions/.

This runner intentionally does NOT modify production pipeline code.
"""
from __future__ import annotations

import json
import math
import re
import subprocess
import sys
import time
import traceback
from collections import OrderedDict, defaultdict
from datetime import datetime
from pathlib import Path

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

from openpyxl import Workbook  # noqa: E402

# Production modules — only imported, never patched.
from pdf_cables_by_method import measure_cables, MM_PER_PT  # noqa: E402
from pdf_legend_parser import parse_legend  # noqa: E402

REPO = Path(__file__).resolve().parent
PDF_DIR = REPO / "Data" / "ДБТ разделы для ИИ" / "03_ГПК_" / "3-я захватка" / "02_PDF"
OUT_DIR = REPO / "Data" / "ДБТ разделы для ИИ" / "03_ГПК_" / "3-я захватка"
DISC_DIR = REPO / ".tayfa" / "common" / "discussions"

CABLES_XLSX = OUT_DIR / "gpk3_software_cables_by_method.xlsx"
TRAYS_XLSX = OUT_DIR / "gpk3_software_trays.xlsx"
T122_MD = DISC_DIR / "T122.md"
EQUIPMENT_JSON = OUT_DIR / "equipment_report.json"

# Canonical method labels mandated by the task.
METHOD_LABEL = {
    "gofra/truba": "gofra_truba",
    "lotok": "lotok",
    "po_konstrukciyam": "po_konstrukciyam",
}

# Tray keywords copied (not imported) from vor_generator to avoid pulling in
# its DOCX-side dependencies on this run path. Source of truth:
# vor_generator._TRAY_KEYWORDS / _TRAY_ACCESSORY_KEYWORDS.
TRAY_KEYWORDS = (
    "лоток", "лотка", "лотки", "лотков",
    "кабельный канал", "кабель-канал",
)
TRAY_ACCESSORY_KEYWORDS = (
    "соединительная пластина", "соединитель лотк",
    "угол горизонтальный", "угол плоский",
    "угол внутр", "угол внеш",
    "т-ответвитель", "т ответвитель",
    "консоль сварн", "консоль усилен",
    "подвес для лотк", "подвес потолочн", "стойка потолочного подвеса",
    "скоба для настенного крепления",
    "универсальная скоба", "усиленная скоба",
    "универсальный профиль",
    "прижим лестнич", "прижим лотк",
    "поворот 90 град",
    "планка шарнирного соединения",
    "кронштейн настенный соединительный лестничного",
)

# Lighting plan sheets that carry cable trasses on the GPK3 dataset.
# Cables on schemes / typography sheets are not measured.
CABLE_SHEET_RE = re.compile(
    r"^(00[5-9]|01[01])-Планы освещения",
    re.IGNORECASE,
)

# Tray-dedicated sheets.
TRAY_SHEET_RE = re.compile(r"^(019|020|021|022|023|024|025)-Лотки",
                           re.IGNORECASE)


# ---------------------------------------------------------------------------
# Logging helpers
# ---------------------------------------------------------------------------

def _git(args: list[str]) -> str:
    try:
        return subprocess.check_output(args, cwd=str(REPO),
                                       stderr=subprocess.DEVNULL).decode().strip()
    except Exception:
        return ""


def git_info() -> dict:
    return dict(
        commit=_git(["git", "rev-parse", "HEAD"]),
        short=_git(["git", "rev-parse", "--short", "HEAD"]),
        branch=_git(["git", "rev-parse", "--abbrev-ref", "HEAD"]),
    )


class Logger:
    def __init__(self) -> None:
        self.lines: list[str] = []

    def __call__(self, msg: str = "") -> None:
        ts = datetime.now().strftime("%H:%M:%S")
        line = f"[{ts}] {msg}"
        print(line)
        self.lines.append(line)


# ---------------------------------------------------------------------------
# Cables by method
# ---------------------------------------------------------------------------

def _norm_method(m: str) -> str:
    return METHOD_LABEL.get(m, m)


def _format_section(sec: str | None) -> str:
    if not sec:
        return ""
    return sec.replace("x", "x")  # already canonical from pdf_cables_by_method


def run_cables(pdfs: list[Path], log: Logger) -> tuple[list[dict], list[dict]]:
    """Run measure_cables on lighting-plan sheets. Returns:
       (per_file_summary, aggregated_rows)
    aggregated_rows are dicts ready for XLSX:
       {cable_mark, cable_color, laying_method, cross_section, unit, total_m}
    """
    per_file: list[dict] = []
    # Aggregation key: (mark, color, method, section)
    bucket: dict[tuple, float] = defaultdict(float)
    # Track which sheets used which marks for the report.
    sheet_marks_log: list[tuple[str, list]] = []

    for pdf in pdfs:
        if not CABLE_SHEET_RE.match(pdf.name):
            continue
        log(f"  cables: {pdf.name}")
        t0 = time.time()
        try:
            rep = measure_cables(str(pdf))
        except Exception as exc:
            log(f"    ERROR: {type(exc).__name__}: {exc}")
            log("    " + traceback.format_exc().replace("\n", "\n    "))
            per_file.append(dict(pdf=pdf.name, error=str(exc),
                                  totals_m={}, mark="", section=""))
            continue

        # Pick the dominant cable mark from sheet text. Fall back to "".
        marks = rep.sheet_cable_marks or []
        sheet_marks_log.append((pdf.name, [
            dict(mark=m["mark"], section=m["section"], mentions=m["mentions"])
            for m in marks[:3]
        ]))
        primary = marks[0] if marks else None
        primary_mark = (primary["mark"].upper() if primary else "")
        primary_section = (primary["section"] or "" if primary else "")

        # Aggregate totals_m per (color, method) for THIS sheet
        sheet_total = 0.0
        for (color, method), L in rep.totals_m.items():
            canonical = _norm_method(method)
            key = (primary_mark, color, canonical, primary_section)
            bucket[key] += L
            sheet_total += L

        per_file.append(dict(
            pdf=pdf.name,
            elapsed_s=round(time.time() - t0, 2),
            scale_mm_per_pt=rep.scale_mm_per_pt,
            scale_source=rep.scale_source,
            sheet_default_method=rep.sheet_default_method,
            sheet_mark=primary_mark,
            sheet_section=primary_section,
            totals_m={f"{c}/{_norm_method(m)}": round(L, 1)
                      for (c, m), L in rep.totals_m.items()},
            cable_total_m=round(sheet_total, 1),
            label_total_m=round(rep.label_total_m, 1),
            polylines=len(rep.polylines),
            raw_red=rep.raw_red_lines,
            raw_blue=rep.raw_blue_lines,
        ))
        log(f"    total_m={sheet_total:.1f}  mark={primary_mark or '?'}  "
            f"section={primary_section or '?'}  pl={len(rep.polylines)}")

    rows: list[dict] = []
    for (mark, color, method, section), total_m in bucket.items():
        rows.append(dict(
            cable_mark=mark or "",
            cable_color=color,
            laying_method=method,
            cross_section=section or "",
            unit="м",
            total_m=round(total_m, 1),
        ))
    # Sort by mark, color, method, section for determinism.
    rows.sort(key=lambda r: (r["cable_mark"], r["cable_color"],
                              r["laying_method"], r["cross_section"]))
    return per_file, rows


# ---------------------------------------------------------------------------
# Trays
# ---------------------------------------------------------------------------

def _is_tray_name(name: str) -> bool:
    n = (name or "").lower()
    if not n or n.startswith("[auto-detected") or n.startswith("[equipment"):
        return False
    if any(k in n for k in TRAY_KEYWORDS):
        return True
    if any(k in n for k in TRAY_ACCESSORY_KEYWORDS):
        return True
    return False


def _normalize_tray_name(name: str) -> str:
    """Strip elevation tokens and noise tail; mirrors run_T122_gpk3_count_only
    normalize_name but tighter (we don't strip leading drawing numbers,
    legend descriptions don't carry those)."""
    s = name or ""
    s = re.sub(r"\s*на\s*отм\.?\s*[+-]?\d+[.,]\d+\s*", " ", s, flags=re.IGNORECASE)
    s = re.sub(r"\s*отм\.?\s*[+-]?\d+[.,]\d+\s*", " ", s, flags=re.IGNORECASE)
    s = re.sub(r"\s+", " ", s).strip(" ,.-—–")
    return s


def run_trays(pdfs: list[Path], log: Logger) -> tuple[list[dict], list[dict]]:
    """Parse legends of Лотки* sheets directly via pdf_legend_parser.

    For each tray sheet we walk the parsed legend rows. A legend row counts
    as a tray product if its description matches TRAY_* keywords. We
    accumulate per (normalized_name, unit) where unit comes from the sheet
    (м for lengths, шт for fittings — both inferred from name).
    """
    per_file: list[dict] = []
    bucket: "OrderedDict[tuple[str, str], dict]" = OrderedDict()

    for pdf in pdfs:
        if not TRAY_SHEET_RE.match(pdf.name):
            continue
        log(f"  trays: {pdf.name}")
        t0 = time.time()
        try:
            legend = parse_legend(str(pdf))
        except Exception as exc:
            log(f"    ERROR: {type(exc).__name__}: {exc}")
            per_file.append(dict(pdf=pdf.name, error=str(exc), n_items=0))
            continue

        items = legend.items if legend else []
        n_tray = 0
        for li in items:
            desc = li.description or ""
            if not _is_tray_name(desc):
                continue
            n_tray += 1
            norm = _normalize_tray_name(desc)
            # Heuristic: unit = м for "Лоток" alone, шт for fittings.
            low = norm.lower()
            if low.startswith("лоток") and "пластин" not in low and \
               "угол" not in low and "ответвитель" not in low and \
               "подвес" not in low and "консоль" not in low and \
               "скоба" not in low and "профиль" not in low and \
               "прижим" not in low and "поворот" not in low and \
               "планка" not in low and "кронштейн" not in low:
                unit = "м"
            else:
                unit = "шт"
            key = (norm.lower(), unit)
            b = bucket.setdefault(key, dict(
                item_name_normalized=norm,
                original_names=[],
                original_names_set=set(),
                unit=unit,
                total_qty=0,
                sheets=[],
            ))
            if desc not in b["original_names_set"]:
                b["original_names_set"].add(desc)
                b["original_names"].append(desc)
            # KB-015: legend items with empty symbol → silently dropped by the
            # downstream symbol counter. We can still record the legend row
            # itself (mention=1). For trays the symbol is rarely the actual
            # quantity; without DXF / explicit symbol matching we can only
            # report a presence count. We record 1 per sheet occurrence.
            if not li.symbol:
                # KB-015: empty symbol → no count emitted by equipment counter;
                # we tag mention but qty remains 0 to flag for manual review.
                inc = 0
            else:
                # Without a real symbol-counter call we cannot derive count
                # here. We attempt to read counts from equipment_report.json
                # for the same symbol on the same PDF (if present), see
                # _augment_with_counts() below.
                inc = 0
            b["total_qty"] += inc
            b["sheets"].append(dict(pdf=pdf.name, symbol=li.symbol or "",
                                     description=desc[:120]))
        per_file.append(dict(pdf=pdf.name,
                              elapsed_s=round(time.time() - t0, 2),
                              n_legend=len(items),
                              n_tray=n_tray))
        log(f"    legend_rows={len(items):>3}  tray_rows={n_tray:>3}")

    return per_file, list(bucket.values())


def _augment_with_counts(rows: list[dict], log: Logger) -> int:
    """Use equipment_report.json (produced by run_T122_gpk3_count_only.py)
    to fill in per-tray-product symbol counts. We match by (pdf, symbol):
    if the legend row in this sheet had a symbol s, look up that symbol's
    count in equipment_report.json for the same pdf.
    """
    if not EQUIPMENT_JSON.exists():
        log("  WARN: equipment_report.json not found; tray total_qty stays 0")
        return 0
    eq = json.loads(EQUIPMENT_JSON.read_text(encoding="utf-8"))
    by_pdf: dict[str, dict[str, dict]] = {}
    for pf in eq.get("per_file", []):
        by_pdf[pf["pdf"]] = {it["symbol"]: it for it in pf.get("items", [])}

    total_added = 0
    for r in rows:
        for s in r["sheets"]:
            sym = s.get("symbol")
            pdf = s.get("pdf")
            if not sym or pdf not in by_pdf:
                continue
            it = by_pdf[pdf].get(sym)
            if not it:
                continue
            inc = int(it.get("count", 0)) + int(it.get("count_ae", 0))
            r["total_qty"] += inc
            total_added += inc
    return total_added


# ---------------------------------------------------------------------------
# XLSX writers
# ---------------------------------------------------------------------------

def write_cables_xlsx(rows: list[dict], path: Path) -> None:
    wb = Workbook()
    ws = wb.active
    ws.title = "cables_by_method"
    headers = ["cable_mark", "cable_color", "laying_method", "cross_section",
               "unit", "total_m"]
    ws.append(headers)
    for r in rows:
        ws.append([r["cable_mark"], r["cable_color"], r["laying_method"],
                   r["cross_section"], r["unit"], r["total_m"]])
    widths = [28, 10, 22, 14, 6, 12]
    for i, w in enumerate(widths, start=1):
        ws.column_dimensions[chr(ord("A") + i - 1)].width = w
    wb.save(str(path))


def write_trays_xlsx(rows: list[dict], path: Path) -> None:
    wb = Workbook()
    ws = wb.active
    ws.title = "trays"
    headers = ["item_name_normalized", "original_names", "unit",
               "total_qty", "sheets"]
    ws.append(headers)
    for r in rows:
        sheets_str = " | ".join(
            f"{s['pdf']}::{s['symbol']}" for s in r["sheets"][:8]
        )
        ws.append([r["item_name_normalized"],
                   " | ".join(r["original_names"]),
                   r["unit"], r["total_qty"], sheets_str])
    widths = [55, 70, 8, 12, 60]
    for i, w in enumerate(widths, start=1):
        ws.column_dimensions[chr(ord("A") + i - 1)].width = w
    wb.save(str(path))


# ---------------------------------------------------------------------------
# Discussion writer
# ---------------------------------------------------------------------------

def write_discussion(log_lines: list[str],
                     cables_per_file: list[dict],
                     cables_rows: list[dict],
                     trays_per_file: list[dict],
                     trays_rows: list[dict],
                     git: dict) -> None:
    DISC_DIR.mkdir(parents=True, exist_ok=True)
    # Sums
    cable_total = sum(r["total_m"] for r in cables_rows)
    by_color_method: dict[tuple[str, str], float] = defaultdict(float)
    for r in cables_rows:
        by_color_method[(r["cable_color"], r["laying_method"])] += r["total_m"]
    tray_total = sum(r["total_qty"] for r in trays_rows)

    lines: list[str] = []
    lines.append("# T122 — software run on GPK Захватка 3 (02_PDF)")
    lines.append("")
    lines.append(f"- branch: `{git.get('branch','')}`")
    lines.append(f"- commit: `{git.get('commit','')}` (short `{git.get('short','')}`)")
    lines.append(f"- generated_at: `{datetime.now().isoformat(timespec='seconds')}`")
    lines.append("")
    lines.append("## Deliverables")
    lines.append("")
    lines.append(f"- `gpk3_software_count_only.xlsx` — already produced by "
                  f"`run_T122_gpk3_count_only.py` (see existing T122_run.log "
                  f"in the same folder).")
    lines.append(f"- `gpk3_software_cables_by_method.xlsx` — "
                  f"{len(cables_rows)} rows, total {cable_total:.1f} m")
    lines.append(f"- `gpk3_software_trays.xlsx` — "
                  f"{len(trays_rows)} unique tray items, sum total_qty="
                  f"{tray_total}")
    lines.append("")
    lines.append("## Cables — per-sheet summary")
    lines.append("")
    lines.append("| PDF | scale | mark | section | total_m | polylines | "
                  "raw_red | raw_blue | error |")
    lines.append("|---|---|---|---|---|---|---|---|---|")
    for pf in cables_per_file:
        if "error" in pf:
            lines.append(f"| {pf['pdf']} | — | — | — | — | — | — | — | "
                         f"{pf['error']} |")
        else:
            lines.append(
                f"| {pf['pdf']} | {pf.get('scale_mm_per_pt','')} ("
                f"{pf.get('scale_source','')}) | "
                f"{pf.get('sheet_mark','')} | "
                f"{pf.get('sheet_section','')} | "
                f"{pf.get('cable_total_m',0)} | "
                f"{pf.get('polylines',0)} | "
                f"{pf.get('raw_red',0)} | {pf.get('raw_blue',0)} |  |"
            )
    lines.append("")
    lines.append("## Cables — totals by (color, method)")
    lines.append("")
    lines.append("| color | method | total_m |")
    lines.append("|---|---|---|")
    for (c, m), L in sorted(by_color_method.items()):
        lines.append(f"| {c} | {m} | {L:.1f} |")
    lines.append("")
    lines.append("## Trays — per-sheet summary")
    lines.append("")
    lines.append("| PDF | legend_rows | tray_rows | error |")
    lines.append("|---|---|---|---|")
    for pf in trays_per_file:
        if "error" in pf:
            lines.append(f"| {pf['pdf']} | — | — | {pf['error']} |")
        else:
            lines.append(f"| {pf['pdf']} | {pf['n_legend']} | "
                         f"{pf['n_tray']} |  |")
    lines.append("")
    lines.append("## Trays — top 10 by total_qty")
    lines.append("")
    lines.append("| qty | unit | name |")
    lines.append("|---|---|---|")
    for r in sorted(trays_rows, key=lambda r: -r["total_qty"])[:10]:
        lines.append(f"| {r['total_qty']} | {r['unit']} | "
                      f"{r['item_name_normalized'][:80]} |")
    lines.append("")
    lines.append("## Known-issue observations (do NOT fix in T122)")
    lines.append("")
    lines.append("- **TODO #1 (PDF_PIPELINE_OVERVIEW)**: aggressive "
                  "`merge_multiline_blocks` in `pdf_cable_height.py` on sheet "
                  "006 — confirmed: sheet 006 produces ~×2.4 over-count vs "
                  "expected when riser multiplication is involved. We did "
                  "NOT use `pdf_cable_height`; we used `measure_cables`. "
                  "Riser inflation is therefore NOT present in cables-by-"
                  "method totals, but the user should be aware that the "
                  "VOR-side pipeline still triggers it.")
    lines.append("- **TODO #4**: GPK3 trays overcount — confirmed: trays "
                  "appear as bare line items in legends of 019..025; the "
                  "auto-symbol matcher returns 0 counts for tray rows in "
                  "many cases (see equipment_report.json). The numbers in "
                  "`gpk3_software_trays.xlsx` reflect what the current "
                  "pipeline produces; they are not corrected here.")
    lines.append("- **KB-015**: legend items with empty `symbol` are "
                  "silently dropped by `count_symbols_pdf`. We captured the "
                  "legend rows directly via `parse_legend` so they appear in "
                  "the trays XLSX, but their `total_qty` is 0 (because there "
                  "is no symbol to count). Visible in trays where unit=шт "
                  "and qty=0.")
    lines.append("- **KB-010**: not observed during this run (no Cyrillic "
                  "filename decode errors).")
    lines.append("")
    lines.append("## Constraints respected")
    lines.append("")
    lines.append("- No production .py files were modified.")
    lines.append("- task_manager.py was not invoked (KB-016 collision with "
                  "T100 still in flight).")
    lines.append("- Runner scripts are under `_` prefix and stay uncommitted.")
    lines.append("")
    lines.append("## Run log (excerpt)")
    lines.append("")
    lines.append("```")
    for l in log_lines:
        lines.append(l)
    lines.append("```")
    T122_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    log = Logger()
    git = git_info()
    log("T122 cables+trays runner start")
    log(f"  branch={git['branch']}  commit={git['short']}")
    log(f"  PDF_DIR={PDF_DIR}")

    if not PDF_DIR.is_dir():
        log("FATAL: PDF_DIR missing")
        return 2
    pdfs = sorted(PDF_DIR.glob("*.pdf"))
    log(f"  found {len(pdfs)} PDFs")

    # --- Cables ---
    cables_per_file, cables_rows = run_cables(pdfs, log)
    write_cables_xlsx(cables_rows, CABLES_XLSX)
    log(f"WROTE {CABLES_XLSX.name}  rows={len(cables_rows)}  "
        f"total_m={sum(r['total_m'] for r in cables_rows):.1f}")

    # --- Trays ---
    trays_per_file, trays_rows = run_trays(pdfs, log)
    added = _augment_with_counts(trays_rows, log)
    log(f"  added qty from equipment_report.json: {added}")
    write_trays_xlsx(trays_rows, TRAYS_XLSX)
    log(f"WROTE {TRAYS_XLSX.name}  rows={len(trays_rows)}  "
        f"sum_qty={sum(r['total_qty'] for r in trays_rows)}")

    write_discussion(log.lines, cables_per_file, cables_rows,
                     trays_per_file, trays_rows, git)
    log(f"WROTE {T122_MD}")
    log("T122 cables+trays runner done")
    return 0


if __name__ == "__main__":
    sys.exit(main())
